spring.application.name=server
server.port=10061

spring.ssl.bundle.pem.bundle1.keystore.certificate=/var/opt/cert.pem
spring.ssl.bundle.pem.bundle1.keystore.private-key=/var/opt/key.pem
server.ssl.bundle=bundle1
server.ssl.enabled = false
